# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: circleci/node:14.17.0
#     steps:
#       - checkout
#       - run:
#           name: Install dependencies
#           command: npm ci
#       - run:
#           name: Run tests
#           command: npm test
#       - run:
#           name: Build application
#           command: npm run build
#       - deploy:
#           name: Deploy to Heroku
#           command: |
#             heroku container:push web --app=my-heroku-app
#             heroku container:release web --app=my-heroku-app
#           requires:
#             - build
